server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kannan_ecomm
    username: root
    password: '!!June@2023'

  jpa:
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /api

  boot:
    admin:
      client:
        url: http://localhost:1111/

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'kannanlearning2621@gmail.com'
    password: 'yvwr fgbl bwtj intj'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
